## Required parameters
multi_gpu: False
task: "clueweb09"
model: "cknrm"
policy: True
knowledge: False
finetune: False
train: "./data/pretrain/pretrain.tsv"
dev: "./data/ClueWeb09/dev_09_0.tsv"
label: "./data/ClueWeb09/qrels"
out_trec: "./data/ClueWeb09/trec.txt"
epoch: 5
word2vec: "data/vocab.tsv"
vocab_size: 400002
embedding_dim: 300
batch_size: 32
stopword_removal: True
stemming: True
score_feature: True
depth: 20
check_step: 1000
save_model: "./checkpoints/model/model.bin"

## Other parameters
load_model: "./checkpoints/model/model.bin"
#config: "./checkpoints/bert-base/bert_config.json"
max_seq_len: 128
n_kernels: 21
policy: "all"
classify: False
load_policy: "./checkpoints/policy/policy.bin"
channels: 20
gamma: 0.99
k: 4
save_policy: "./checkpoints/policy/policy.bin"
